#!/usr/bin/env python3
"""Rebuild the sample data in src/EVPoint_dump.sql.

Charging stations and connectors come from the Open Charge Map snapshot in
data/ocm_athens_snapshot.json (see tools/fetch_ocm.py). Everything else (users, cars,
health readings, roadside assistance, reviews, occupancy) is fictional and generated
here with a fixed random seed, so running the script twice gives identical output.

The schema and views in src/EVPoint_dump.sql are kept as they are; only the block of
INSERT statements between the schema and the final SET statements is replaced.

Usage:  python3 tools/build_sample_data.py
Needs only the Python 3 standard library.
"""
import datetime as dt
import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / "data" / "ocm_athens_snapshot.json"
DUMP = ROOT / "src" / "EVPoint_dump.sql"

BEGIN = "-- BEGIN SAMPLE DATA (generated by tools/build_sample_data.py)"
END = "-- END SAMPLE DATA"
FOOTER_START = "SET SQL_MODE=@OLD_SQL_MODE;"

NOW = dt.datetime(2026, 9, 30, 14, 0, 0)  # the moment the sample data "is taken"
MAX_STATIONS = 30
MAX_PER_TYPE = 2  # connectors of the same type kept per station

# ---- fictional reference data -------------------------------------------------------

USER_IDS = ["015265", "012546", "056352", "169872", "161099", "368057", "368145",
            "204118", "219377", "233904", "251560", "287731", "301846", "342209"]
# 9 digits on purpose: the schema stores phone numbers in an INT column
USER_PHONES = ["691234568", "692345679", "693456780", "696546875", "695646872", "693685438",
               "695378876", "694120311", "697338204", "698450917", "691577320", "692684433",
               "693791546", "694806659"]
CAR_NAMES = ["Nissan Leaf", "Tesla Model 3", "Renault Zoe", "Hyundai Kona Electric", "VW ID.3",
             "Kia EV6", "Peugeot e-208", "Fiat 500e", "MG4", "BMW i3", "Skoda Enyaq",
             "Opel Corsa-e", "Dacia Spring", "Mini Cooper SE"]
CAR_NOTES = ["Daily commute", "Company car", "Family car", "Weekend trips", "Car sharing",
             "Second car", None]
PLATE_LETTERS = "ABEZHIKMNOPTYX"  # letters used on Greek plates
CITY_CENTRES = {"Thessaloniki": (40.6401, 22.9444), "Patras": (38.2466, 21.7346)}

# name, phone (9 digits, invented), latitude, longitude
RSA = [
    ("Attica Roadside Help", 210555101, 37.9838, 23.7275),
    ("Piraeus Tow and Assist", 210555102, 37.9420, 23.6470),
    ("Northern Suburbs Assist", 210555103, 38.0560, 23.8080),
    ("Saronic Coast Assist", 210555104, 37.8650, 23.7530),
    ("Thessaloniki Road Aid", 231055105, 40.6300, 22.9400),
    ("Patras Road Rescue", 261055106, 38.2450, 21.7350),
]

COMMENTS = {
    1: ["Not for me", "Would not use again", "Did not suit my needs"],
    2: ["Slower than I hoped", "Often busy in the evening", "Hard to find the entrance"],
    3: ["Works fine", "Average station", "Okay for a quick top-up"],
    4: ["Fast and reliable", "Easy to find, good speed", "Rarely a queue"],
    5: ["Excellent, always available", "Fast charging and easy payment",
        "Best station in the area"],
}


# ---- station data from the snapshot ------------------------------------------------

def map_type(title):
    """Map an Open Charge Map connection title to the schema's connectorType enum."""
    t = (title or "").lower()
    if "ccs" in t and "type 1" not in t:
        return "CCS2"
    if "tesla" in t and "roadster" not in t:
        return "Tesla TYPE 2"
    if "type 2" in t and "ccs" not in t:
        return "TYPE 2"
    return None


def clean_operator(raw):
    """Turn Open Charge Map's placeholder operator names into readable ones (max 25 chars)."""
    name = (raw or "").strip()
    low = name.lower()
    if not name or "unknown operator" in low:
        return "Unknown operator"
    if "business owner" in low:
        return "Site owner"
    if low.startswith("tesla"):
        return "Tesla"
    if low.startswith("blink"):
        return "Blink Charging"
    return name[:25].rstrip()


def pick_diverse(candidates, limit):
    """Round-robin over operators so one large network does not fill the whole sample."""
    groups = {}
    for s in candidates:
        groups.setdefault(s["name"], []).append(s)
    for g in groups.values():
        g.sort(key=lambda s: (-len(s["connectors"]), s["ocm_id"]))
    order = sorted(groups, key=lambda n: (n == "Unknown operator", len(groups[n]), n))
    picked = []
    while len(picked) < limit and any(groups.values()):
        for n in order:
            if groups[n] and len(picked) < limit:
                picked.append(groups[n].pop(0))
    return picked


def is_active(station):
    """False for stations Open Charge Map lists as removed, planned or not operational."""
    status = (station.get("status") or "").lower()
    return not any(w in status for w in ("removed", "decommission", "planned", "not operational"))


def station_connectors(station):
    """Connectors of a station that map to a schema type, at most MAX_PER_TYPE of each type."""
    conns, per_type = [], {}
    for c in station.get("connections") or []:
        ctype = map_type(c.get("type"))
        if ctype is None:
            continue
        operational = c.get("operational")
        if operational is None:
            operational = station.get("operational")
        wanted = max(1, int(c.get("quantity") or 1))
        count = max(0, min(wanted, MAX_PER_TYPE - per_type.get(ctype, 0)))
        per_type[ctype] = per_type.get(ctype, 0) + count
        conns += [{"type": ctype, "operational": operational is not False}] * count
    return conns


def load_stations(path):
    """Read the snapshot and return it together with the stations picked for the sample."""
    snap = json.loads(path.read_text(encoding="utf-8"))
    candidates = []
    seen = set()
    for s in snap["stations"]:
        conns = station_connectors(s) if is_active(s) else []
        if not conns:
            continue
        name = clean_operator(s.get("operator"))
        lat, lon = round(float(s["latitude"]), 6), round(float(s["longitude"]), 6)
        if (name, lat, lon) in seen:
            continue
        seen.add((name, lat, lon))
        candidates.append({"ocm_id": s.get("ocm_id") or 0, "name": name, "lat": lat, "lon": lon,
                           "connectors": conns,
                           "provider": s.get("data_provider"),
                           "license": s.get("data_provider_license")})
    stations = sorted(pick_diverse(candidates, MAX_STATIONS), key=lambda s: s["ocm_id"])
    return snap, stations


# ---- fictional data ----------------------------------------------------------------

def near(a_lat, a_lon, b_lat, b_lon, box):
    """True if point b lies inside a square of half-width `box` degrees around point a."""
    return abs(a_lat - b_lat) < box and abs(a_lon - b_lon) < box


def make_connectors(stations):
    """Real connector types; availability 1 = available, -1 = occupied, 0 = out of service."""
    connectors = []
    operational_index = 0
    for st in stations:
        for c in st["connectors"]:
            if not c["operational"]:
                avail = 0
            else:
                operational_index += 1
                avail = -1 if operational_index % 5 == 0 else 1
            connectors.append({"id": 100001 + len(connectors), "type": c["type"],
                               "availability": avail, "station": st})
    return connectors


def make_cars(rng):
    """One car per user, each with a unique Greek-style licence plate."""
    plates = set()
    cars = []
    for i in range(len(USER_IDS)):
        while True:
            letters = "".join(rng.choice(PLATE_LETTERS) for _ in range(3))
            plate = f"{letters}{rng.randint(1000, 9999):04d}"
            if plate not in plates:
                plates.add(plate)
                break
        cars.append({"plate": plate, "name": CAR_NAMES[i % len(CAR_NAMES)],
                     "notes": CAR_NOTES[i % len(CAR_NOTES)]})
    return cars


def make_users(stations, rng, n_athens):
    """The first n_athens users live next to real stations, the rest in Thessaloniki/Patras."""
    users = []
    for i, uid in enumerate(USER_IDS):
        if i < n_athens:
            st = stations[(i * len(stations)) // n_athens]
            lat = st["lat"] + rng.uniform(-0.02, 0.02)
            lon = st["lon"] + rng.uniform(-0.02, 0.02)
        else:
            c_lat, c_lon = CITY_CENTRES[["Thessaloniki", "Patras"][i - n_athens]]
            lat = c_lat + rng.uniform(-0.01, 0.01)
            lon = c_lon + rng.uniform(-0.01, 0.01)
        users.append({"id": uid, "phone": USER_PHONES[i],
                      "lat": round(lat, 6), "lon": round(lon, 6)})
    return users


def make_health(cars, rng):
    """Two or three health readings per car in the last ten days."""
    health = []
    for car in cars:
        used = set()
        for _ in range(rng.randint(2, 3)):
            ts = NOW - dt.timedelta(days=rng.randint(0, 9), hours=rng.randint(0, 23),
                                    minutes=rng.randint(0, 59))
            ts = ts.replace(second=0)
            if ts in used:
                continue
            used.add(ts)
            health.append({"ts": ts, "plate": car["plate"],
                           "engine": rng.uniform(70, 99), "battery": rng.uniform(60, 99),
                           "tirep": rng.uniform(30, 38), "tirec": rng.uniform(60, 99),
                           "pct": rng.uniform(10, 95)})
    health.sort(key=lambda h: (h["plate"], h["ts"]))
    return health


def make_occupancy(connectors, cars, rng):
    """Running sessions on every occupied connector, plus some finished ones."""
    occupied, pairs = [], set()
    car_pool = cars[:]
    rng.shuffle(car_pool)
    busy = [c for c in connectors if c["availability"] == -1]
    for c, car in zip(busy, car_pool):
        start = NOW - dt.timedelta(minutes=rng.randint(10, 90))
        occupied.append({"cid": c["id"], "plate": car["plate"], "from": start, "until": None,
                         "est": NOW + dt.timedelta(minutes=rng.randint(10, 80))})
        pairs.add((c["id"], car["plate"]))
    free = [c for c in connectors if c["availability"] == 1]
    for _ in range(8):
        c, car = rng.choice(free), rng.choice(cars)
        if (c["id"], car["plate"]) in pairs:
            continue
        pairs.add((c["id"], car["plate"]))
        start = (NOW - dt.timedelta(days=rng.randint(1, 10))).replace(hour=rng.randint(7, 21),
                                                                      minute=rng.randint(0, 59))
        end = start + dt.timedelta(minutes=rng.randint(30, 150))
        occupied.append({"cid": c["id"], "plate": car["plate"], "from": start, "until": end,
                         "est": end + dt.timedelta(minutes=rng.randint(-10, 10))})
    return occupied


def make_calls(users, rng):
    """Roadside assistance calls, only from users inside a provider's 0.1 degree box."""
    calls = []
    for u in users:
        nearest = [r for r in RSA if near(u["lat"], u["lon"], r[2], r[3], 0.1)]
        if nearest and len(calls) < 6:
            ts = NOW - dt.timedelta(days=rng.randint(1, 20), minutes=rng.randint(0, 1439))
            calls.append({"uid": u["id"], "rsa": nearest[0][1], "ts": ts,
                          "lat": round(u["lat"] + rng.uniform(-0.003, 0.003), 6),
                          "lon": round(u["lon"] + rng.uniform(-0.003, 0.003), 6)})
    return calls


def make_reviews(users, stations, rng):
    """Each user reviews 2-4 stations near them; the last stations stay unreviewed."""
    reviewable = stations[:-4] if len(stations) > 8 else stations
    reviews, keys = [], set()
    for u in users:
        close = [s for s in reviewable
                 if near(u["lat"], u["lon"], s["lat"], s["lon"], 0.15)] or reviewable
        for s in rng.sample(close, min(len(close), rng.randint(2, 4))):
            stars = rng.choices([1, 2, 3, 4, 5], weights=[1, 2, 3, 5, 4])[0]
            date = dt.date(2026, 6, 1) + dt.timedelta(days=rng.randint(0, 120))
            key = (u["id"], s["name"], s["lat"], s["lon"], date)
            if key in keys:
                continue
            keys.add(key)
            reviews.append({"uid": u["id"], "station": s, "stars": stars,
                            "comment": rng.choice(COMMENTS[stars]), "date": date})
    return reviews


def generate(stations, rng):
    """Build all fictional sample data around the real stations."""
    n_athens = len(USER_IDS) - 2  # plus 1 user in Thessaloniki and 1 in Patras
    connectors = make_connectors(stations)
    cars = make_cars(rng)
    users = make_users(stations, rng, n_athens)
    # everyone drives and owns their own car; three cars are shared
    drives = [(car["plate"], user["id"]) for car, user in zip(cars, users)]
    for car_i, user_i in ((3, 4), (7, 8), (9, 2)):  # never the user with id 012546 (index 1)
        drives.append((cars[car_i]["plate"], users[user_i]["id"]))
    owns = [(user["id"], car["plate"]) for car, user in zip(cars, users)]
    return {
        "connectors": connectors,
        "cars": cars,
        "users": users,
        "drives": drives,
        "owns": owns,
        "health": make_health(cars, rng),
        "occupied": make_occupancy(connectors, cars, rng),
        "rsa": RSA,
        "calls": make_calls(users, rng),
        "reviews": make_reviews(users[:n_athens], stations, rng),
    }


# ---- SQL rendering ------------------------------------------------------------------

def q(v):
    """Quote a value as an SQL string literal (NULL for None)."""
    if v is None:
        return "NULL"
    return "'" + str(v).replace("\\", "\\\\").replace("'", "''") + "'"


def coord(x):
    """Quote a coordinate with six decimals."""
    return q(f"{x:.6f}")


def num3(x):
    """Quote a number with three decimals."""
    return q(f"{x:.3f}")


def stamp(t):
    """Quote a datetime as an SQL timestamp (NULL for None)."""
    return q(t.strftime("%Y-%m-%d %H:%M:%S")) if t else "NULL"


def insert(table, columns, rows):
    """One INSERT statement per row."""
    cols = ", ".join(f"`{c}`" for c in columns)
    return [f"INSERT INTO `evpointdb`.`{table}` ({cols}) VALUES ({', '.join(r)});" for r in rows]


def render(snap, stations, d):
    """Render the complete sample data block as SQL."""
    out = [BEGIN, "--"]
    out += ["-- Charging stations and connectors: snapshot of Open Charge Map data",
            f"-- (https://openchargemap.org), taken {snap['fetched_at_utc']}, CC BY 4.0. "
            "Each station keeps the licence of its",
            "-- original data provider. Users, cars, health readings, roadside assistance, "
            "reviews and",
            "-- occupancy below are FICTIONAL sample data.",
            "--",
            "-- connector.availability: 1 = available, -1 = occupied, 0 = out of service",
            "-- occupiedconnector.occupiedUntil is NULL while a session is still running.",
            ""]
    out += insert("car", ["licenseNumber", "name", "photo", "notes"],
                  [[q(c["plate"]), q(c["name"]), "NULL", q(c["notes"])] for c in d["cars"]])
    out.append("")
    out += insert("chargingstation", ["companyName", "latitude", "longtitude"],
                  [[q(s["name"]), coord(s["lat"]), coord(s["lon"])] for s in stations])
    out.append("")
    out += insert("connector",
                  ["connectorID", "connectorType", "availability", "chargingStation_companyName",
                   "chargingStation_latitude", "chargingStation_longtitude"],
                  [[q(c["id"]), q(c["type"]), q(c["availability"]), q(c["station"]["name"]),
                    coord(c["station"]["lat"]), coord(c["station"]["lon"])]
                   for c in d["connectors"]])
    out.append("")
    out += insert("health",
                  ["healthTimeStamp", "engineHealth", "batteryHealth", "tirePressure",
                   "tireCondition", "batteryPercentage", "Car_licenseNumber"],
                  [[stamp(h["ts"]), num3(h["engine"]), num3(h["battery"]), num3(h["tirep"]),
                    num3(h["tirec"]), num3(h["pct"]), q(h["plate"])] for h in d["health"]])
    out.append("")
    out += insert("occupiedconnector",
                  ["OccupiedConnectorID", "connectedCarLN", "occupiedFrom", "occupiedUntil",
                   "occupiedEstimatedUntil"],
                  [[q(o["cid"]), q(o["plate"]), stamp(o["from"]), stamp(o["until"]),
                    stamp(o["est"])] for o in d["occupied"]])
    out.append("")
    out += insert("rsa", ["phoneNumber", "name", "longtitude", "latitude"],
                  [[q(r[1]), q(r[0]), coord(r[3]), coord(r[2])] for r in d["rsa"]])
    out.append("")
    out += insert("user", ["userID", "phoneNumber", "longtitude", "latitude"],
                  [[q(u["id"]), q(u["phone"]), coord(u["lon"]), coord(u["lat"])]
                   for u in d["users"]])
    out.append("")
    out += insert("user_calls_rsa",
                  ["User_userID", "RSA_phoneNumber", "timestamp", "callerLattitude",
                   "callerLongtitude"],
                  [[q(c["uid"]), q(c["rsa"]), stamp(c["ts"]), coord(c["lat"]), coord(c["lon"])]
                   for c in d["calls"]])
    out.append("")
    out += insert("user_drives_car", ["car_licenseNumber", "user_userID"],
                  [[q(p), q(u)] for p, u in d["drives"]])
    out.append("")
    out += insert("user_owns_car", ["User_userID", "Car_licenseNumber"],
                  [[q(u), q(p)] for u, p in d["owns"]])
    out.append("")
    out += insert("user_reviews_chargingstation",
                  ["User_userID", "chargingStation_companyName", "chargingStation_latitude",
                   "chargingStation_longtitude", "stars", "comment", "date"],
                  [[q(r["uid"]), q(r["station"]["name"]), coord(r["station"]["lat"]),
                    coord(r["station"]["lon"]), q(r["stars"]), q(r["comment"]),
                    q(r["date"].isoformat())]
                   for r in d["reviews"]])
    out += ["", END, ""]
    return "\n".join(out)


def splice(text, block):
    """Replace the data block (or, on the first run, the old INSERT statements)."""
    footer_at = text.rfind(FOOTER_START)
    if footer_at < 0:
        sys.exit(f"Could not find the closing SET statements in {DUMP}")
    if BEGIN in text:
        head = text[:text.index(BEGIN)]
    else:
        first = text.find("INSERT INTO")
        if first < 0:
            sys.exit(f"Could not find where the sample data starts in {DUMP}")
        head = text[:first]
    return head + block + "\n" + text[footer_at:]


def main():
    """Rebuild the sample data block in the dump and print a short summary."""
    if not SNAPSHOT.exists():
        sys.exit(f"Missing {SNAPSHOT}. Run tools/fetch_ocm.py first.")
    snap, stations = load_stations(SNAPSHOT)
    if len(stations) < 10:
        sys.exit(f"Only {len(stations)} usable stations in the snapshot; need at least 10. "
                 "Try fetching a larger radius.")
    rng = random.Random(20260930)
    data = generate(stations, rng)
    text = DUMP.read_text(encoding="utf-8")
    DUMP.write_text(splice(text, render(snap, stations, data)), encoding="utf-8", newline="\n")

    providers = sorted({(s["provider"] or "unknown", s["license"] or "no licence text")
                        for s in stations})
    print(f"Stations: {len(stations)}, connectors: {len(data['connectors'])}, "
          f"users: {len(data['users'])}, cars: {len(data['cars'])}, "
          f"reviews: {len(data['reviews'])}")
    print(f"Snapshot date: {snap['fetched_at_utc']}")
    print("Data providers among the selected stations (for the README attribution):")
    for name, lic in providers:
        print(f"  - {name}: {lic}")


if __name__ == "__main__":
    main()
